### ISSUE TITLE
USER STORY: Django/Libraries Install

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#18]
As a **Developer** I can **set up Django and install the supporting libraries predicted to be needed** so that **I am ready to start development**

## Acceptance Criteria
- Django installed and Django success page displayed when running server
- Libraries installed and added to requirements.txt

## Tasks
- [x] Task 1 - Install Django
- [x] Task 2 - Install predicted libraries based off Boutique Ado
- [x] Task 3 - Create a requirements.txt file
- [x] Task 4 - Freeze requirements.txt file

**Comment by seanf316** [comment]
Predicted libraries for site installed and project pchaven created - 76e8d39b650f501780b48d65755def34992469dd

**Comment by seanf316** [comment]
Install djrichtextfield for use in future apps and added config to settings.py - 139db3770f69a12c57a3067821b495fd9b6c95c2

**Comment by seanf316** [comment]
Installed Django Resized to format images on upload - f60050d98a21eb75d74ea3d76e1adcaa39b59571
