### ISSUE TITLE
USER STORY: Secure Site Keys/Variables

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#19]
As a **Developer** I need **to create the env.py and add to .gitignore** so that **I can securely deploy the site without exposing developer keys/information**

## Acceptance Criteria
- Create env.py and add secure variables
- Update settings.py to point to env.py for specified variables

## Tasks
- [x] Task 1 - Create env.py
- [x] Task 2 - Create ElephantSQL database
- [x] Task 3 - Update settings.py to point to env.py for Variables/Keys
- [x] Task 4 - Add the env.py file to the .gitignore file so that it does not get pushed to GitHub

**Comment by seanf316** [comment]
ElephantSQL database setup and secret key generated, env.py created and settings.py updated to point to env.py for keys/variables to keep site secure - 5c8919f39e67545eb8ba6b966b195f6a6755b146

Further keys/variables will be added before deployment.

**Comment by seanf316** [comment]
Settings.py/env.py updated with Stripe Variables - 5d615b25f6f5b5c073440204d65c7e733265af4a
