### ISSUE TITLE
USER STORY: Create AWS Groups/Policies and Users

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#20]
As a **Developer** I can **setup the AWS Groups/Policies and Users ** so that **so that the hosted static and media files are available to site when deployed.**

## Acceptance Criteria
- When site is deployed static and media files are displayed as expected on site

## Tasks
- [x] Task 1 - Create new bucket
- [x] Task 2 - Create Groups/Policies and Users
- [x] Task 3 - Connect Django to S3

**Comment by seanf316** [comment]
AWS S3 bucket created along with IAM Groups/Policies and Users. custom_storages.py created and settings.py updated with AWS config - 18aa04f09b2c98246feb9de269352441d4244869

I will be doing more testing once I have started uploaded files.

**Comment by seanf316** [comment]
Media files added to bucket and tests confirm both static and media files working as expected.
