### ISSUE TITLE
USER STORY: Early Deployment to Heroku

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#21]
As a **Developer** I can **deploy site to Heroku early** so that **I can confirm everything works before development of the site and to enable continuous testing within the production environment**

## Acceptance Criteria
- Heroku config vars updated
- Github automatic deploys selected
- App deploys and launches without issue

## Tasks
- [x] Task 1 - Create a new Heroku App
- [x] Task 2 - Update app Config Vars
- [x] Task 3 - Link to Github for automatic deployment
- [x] Task 4 - Add Heroku app name to Allowed Hosts in settings.py
- [x] Task 4 - Configure the settings.py file with to point at the correct env.py file in development, the os in deployment and adjust the database section to point at the correct database url from Heroku.

**Comment by seanf316** [comment]
Added Procfile and setup Heroku app as well as config vars - 325d06ec6d9bd2b03b4ec1cb0cea1e0150e218b6

**Comment by seanf316** [comment]
Static files tested and are successfully populating on the site.
