### ISSUE TITLE
USER STORY: Base Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#22]
As a **Developer** I can **build a base template** so that **it can be extended to any templates that may require it**

## Acceptance Criteria
When the template is extended to another template all html code is applied i.e. Navbar/Footer

## Tasks
- [x] Task 1 - Create Base Template html code
- [x] Task 2 - Add Navbar
- [x] Task 3 - Add Footer
- [x] Task 4 - Make responsive on all devices (Install Bootstrap)

**Comment by seanf316** [comment]
base.html created and bootstrap installed - 51246b0b464410c564297ac17425ffe69679099a

Further changes to be made on base.html.

**Comment by seanf316** [comment]
Navbar created and styled - a80c7fb7279f05065b7808aa7ea7399eab2f01a0

**Comment by seanf316** [comment]
Updated Base.html layout - f4d0af491686151b67b695be32f1452069d9efbd

**Comment by seanf316** [comment]
Updated layout/links of Navbar. Navbar styled also - 622b384529fcd9399c107041b6ecda99c46ebe20

**Comment by seanf316** [comment]
Updated All Products link in navbar - 1407d8a0f5ded900e98ad6c92490efdff2f220a5

**Comment by seanf316** [comment]
Navbar mega menu created in dropdown - 904a32a1d13cbeea82c8411e7f4766c0fd5e5622

**Comment by seanf316** [comment]
All nav related code moved into a single navbar.html file - 50f0fc4b30179dd60134f83ad3716303f70e826a

**Comment by seanf316** [comment]
Updated navlinks to use the products context processor - 8502ad49cfea1f16caec605dba9b5f0d50aa472d

**Comment by seanf316** [comment]
Updated Nav menu to include a sort products by sub-category link - ef0e5252763d6814e0af9438d7793a0beff68675

**Comment by seanf316** [comment]
Updated Nav menu to include Product Management link - a5c0566f032217eebf4daf08b54a44eedc109b08

**Comment by seanf316** [comment]
Cart count added to navbar - 71ab2c4061e12165773c5cb10ee58f2479d66de6

**Comment by seanf316** [comment]
Stripe js script added to corejs block - 86f36b7895a4c026ea30ecc5876142ec7acc4bc0

**Comment by seanf316** [comment]
Navbar updated with Profile link - 42f37ca90a970d1c4562755f56e1131f99e7b474

**Comment by seanf316** [comment]
Contact link updated in Navbar - 7337b2e500440cfb65b9e4ae25f902decf8fc018

**Comment by seanf316** [comment]
Blog link updated in Navbar - 43cfe853ea5663b2f4a690e219462a9d6989b0fd

**Comment by seanf316** [comment]
Added Blog Management link to Navbar - 1db231a9ae2ffbb20126358083bffd830500b5f4

**Comment by seanf316** [comment]
Added Owl scripts to Base template - 322453a5764a3c51347ec25066155a465f64701b

**Comment by seanf316** [comment]
Added mx-auto to mobile ul - 93fbd699fe16a453b0d5d3bf0587995f6a4ebb9e

**Comment by seanf316** [comment]
About us link updated in Navbar - c83dc4f262924d065a7a9cb8135b1dc7ce0cf9b0

**Comment by seanf316** [comment]
BTT removed from templates, added to base instead- f441aec58b47c889bc9c58cf9b173fa31de11d48

**Comment by seanf316** [comment]
Footer added - d9c5402db660627b77c7d6d7cfc8391ff75172b6
