### ISSUE TITLE
USER STORY: Site Homepage

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#23]
As a **Developer** I can **design an aesthetically pleasing Homepage** so that **users have a positive experience when visiting the site**

## Acceptance Criteria
Homepage is created and is responsive on all devices
User can easily identify what the site is about based off the landing page

## Tasks
- [x] Task 1 - Create Homepage view
- [x] Task 2 - Update Urls
- [x] Task 3 - Design Homepage Template
- [x] Task 4 - Add styling

**Comment by seanf316** [comment]
Homepage created and styled inline with site theme - 0d234c6eff933fe7b6b4bc1647a39f47a4a08411

Further content to be added to the Homepage.

**Comment by seanf316** [comment]
Updated Homepage layout/styling - f4d0af491686151b67b695be32f1452069d9efbd

**Comment by seanf316** [comment]
Added new hero image and background svg for the landing page - e841787883c4101cec45ba8cbf1cb1fc0dcb4880

**Comment by seanf316** [comment]
Adjusted landing page text to center - 4d8693eeea383c447735d436581a366ece6ba0e8

**Comment by seanf316** [comment]
Updated landing page welcome text - 6f60c4c3387812c87d891fbdf389f01e3619fa00

**Comment by seanf316** [comment]
Home view updated with featured/latest products fields - 0619b9b1afcf8acc63cee9659f1286455da81d4b

**Comment by seanf316** [comment]
Homepage updated with About/Featured Products/Latest Products sections - ab24d1d2c2d1c6c9c1ed786c46c9c731ebc0b0f8

**Comment by seanf316** [comment]
Added privacy and terms view to home views - c004efca97181c1318666bf6a8f38b761225b02c

**Comment by seanf316** [comment]
privacy_policy page created - 6cbaddd4dcd3e41e63a3154dc348170bb3a319c9

**Comment by seanf316** [comment]
terms and conditions page created - f4cc2af6ac1280c019181572ec724df06bfe4ad9

**Comment by seanf316** [comment]
testimonials section added - 139389f4d83d0d50ab9e4876159a0af100702f09

**Comment by seanf316** [comment]
index updated to have includes - 96f51ae4ae29eb3c3ea92d9b3059e60fd28898f5

**Comment by seanf316** [comment]
Added ids to homepage sections - d4a3aee2501ada96927ff61c5ebf219dde0dc9a4

**Comment by seanf316** [comment]
testimonials styling updated - 46df44f4673db43b10e5edece0ee06c957131398

**Comment by seanf316** [comment]
Sale_products added to home view - https://github.com/seanf316/PC-Haven/commit/61774e1ccd9b38c8a1604740e963ef2980145a24

**Comment by seanf316** [comment]
sale_products include added to home templates - https://github.com/seanf316/PC-Haven/commit/3e8bdb772f0f0c712502d0546e183bf566ccb252

**Comment by seanf316** [comment]
sale_products section added to Homepage - https://github.com/seanf316/PC-Haven/commit/e3893736515db6dfd4026f433db5fcc463e047c3
