### ISSUE TITLE
USER STORY: User Sign Up/Login/Logout

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#24]
As a **User** I want to **Sign Up/Login and Logout** so that **I can see what features are available to registered users**

## Acceptance Criteria
- Users are able to Sign Up
- Registered Users are able to Login/Logout

## Tasks
- [x] Task 1 - Install Allauth
- [x] Task 2 - Style pages to match site theme
- [x] Task 3 - Alter Navbar so relevant views are displayed to registered Users

**Comment by seanf316** [comment]
AllAuth templates copied and saved in templates directory - 5e455e8c3a70e33724d0e13a8c73b26b6b104755

**Comment by seanf316** [comment]
AllAuth templates styled and updated Navbar links to reflect i.e Register/Login/Logout - 3b1ba56d71f3c11c9ddd9e86cce9ca8dda8f329f
