### ISSUE TITLE
USER STORY: Email setup for Verification/Password Reset

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#25]
As a **Developer** I can **add functionality to verify email and reset password** so that **the user has better security over their email being used and can reset password if they forget it**

## Acceptance Criteria
- Users receive emails from the site email address for emails like Verification, Password Reset, 

## Tasks
- [x] Task 1 - Create email address for site
- [x] Task 2 - Update site name in Django admin view
- [x] Task 3 - Update allauth email settings in settings.py
- [x] Task 4 - Store private email keys in env.py
- [x] Task 5 - Update Heroku config vars

**Comment by seanf316** [comment]
Gmail Account created for PC Haven.

Site name updated in Django admin settings.

AllAuth email settings applied to settings.py and email keys added to env.py. Heroku config vars updated - 5e455e8c3a70e33724d0e13a8c73b26b6b104755

**Comment by seanf316** [comment]
Email verification and Password Reset setup and tested in test and production environments.
