### ISSUE TITLE
USER STORY: Implement/Create Products

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#26]
As a **Developer** I can **create functional code to apply Products to my site** so that **the customer has Products to purchase**

## Acceptance Criteria
- Products can be added to site through the admin view

## Tasks
- [x] Task 1 - Create Products app
- [x] Task 2 - Update app in settings.py
- [x] Task 3 - Create Model/Views
- [x] Task 4 - Update Products items to database

**Comment by seanf316** [comment]
Products app added and pchaven urls.py updated with products urls - e1ef2ee19ca1486f3501c0741ae5160740109fff

**Comment by seanf316** [comment]
Product, Category and Sub Category models created and migrated - 278267630face3188fc70e289f65f0f192f1e7fd

**Comment by seanf316** [comment]
Added missing fields to Product model - da4ce3530a3a2a6e3b26cc5f1c70067875bea74e

**Comment by seanf316** [comment]
All Product models registered - 330057eb7c14fc744437e8cd91b33852c6f078e4

**Comment by seanf316** [comment]
Customised the Products admin panel - 76466497884127cb975fa3be9b9d1ffb81f9fc8d

**Comment by seanf316** [comment]
Changed Product image upload location in AWS bucket - 36fba68f581be1d5c56e266f1b2cb7dc2f44c3c6

**Comment by seanf316** [comment]
All PC Cases products created and added to database - e72671069eabb447b00e48a71fafdb0ad4f4c5da

**Comment by seanf316** [comment]
Updated stock levels field to have a minimum value - f5d345225b30aa6887afccad26aedbd27c30aa54

**Comment by seanf316** [comment]
Fixed minimum stock level value to 0 - 3656e506d2b390ca97d2a40f65584307572a67b7

**Comment by seanf316** [comment]
Changed the list display for products to manage items easier - 20df98b3ffd782dab8176b2c0bcd8a5ba689a080

**Comment by seanf316** [comment]
Removed product placeholder image due to issue with Resizefield in django not accepting a placeholder - 0ab256ac71caaf8f04f8e0bcd3649d34840474f7

**Comment by seanf316** [comment]
subcategories field ManytoMany field added to CategoryGroup model - fd0203c0785ed4d203d7791346a7df19e09249e8

**Comment by seanf316** [comment]
Pagination added to all products view - eec3eb0de2ba9cdfa2c130a65c27b0fd1c7d827b

**Comment by seanf316** [comment]
Added sorting to the allproducts view - 71e5c10f8ac71a4d8e2c57f3def755556c2c0cb2

**Comment by seanf316** [comment]
Pagination updated to include sorting - 1598e326e615db6f00035c783f2e86941c54ad2f

**Comment by seanf316** [comment]
products context processor created to gather categories for links/badges - 32c0b5a8cd7298f5d1f3c5890e91ba2f93802ac6

**Comment by seanf316** [comment]
products context processor added to settings.py - bb2018693d32a4bd5499c5d8912c23e4602a28e3

**Comment by seanf316** [comment]
selected category variable added to allproducts view to fix badge issue - 00fd708b3a24ffde3ffba61eb9d15c02f8d3db6a

**Comment by seanf316** [comment]
Add product view created - 3ffd62ad8d5b55ef50842b924c3a9e9aec104703

**Comment by seanf316** [comment]
Updated urls with add product view - b60b134389163c67cbe7b31c1efec35cc1e7cc3e

**Comment by seanf316** [comment]
Product/Category/Subcategory forms created - 0ee66baaa2db38181cfd48e09e266657d15b94e2

**Comment by seanf316** [comment]
Product management template created to manage adding a product - 534747a0be4a9806edfe4715d7f7248437a82c72

**Comment by seanf316** [comment]
Custom clearable widget created for add/edit views - 5fb9ade41fb6cd6579c27ea869d34ae2c429f361

**Comment by seanf316** [comment]
Added max validator to stock level - a151808fbbf2ab7045530df2b3ef7359dfa82b6b

**Comment by seanf316** [comment]
allproducts view update with wishlist reference - 0a01be5d9da559f384bcaf773f06d36115bb0965

**Comment by seanf316** [comment]
Wishlist anchors updated on all Product templates - 0526652f0fcfe80bf5916c27a9e8b944207570bf

**Comment by seanf316** [comment]
Product views updated to fix wishlist logic - 614ac346d6fade16c9d69fc7f720549f0b3d96a4

**Comment by seanf316** [comment]
Product page updated with remove from wishlist anchor - f983fda8d7fc935fe96ba4390632490be5bee58b

**Comment by seanf316** [comment]
Product views updated with Review references - dc3c94ab1cb47eac3bebf70d009f4f9eea2874aa

**Comment by seanf316** [comment]
Added featured_product field to Product model - 3c0a832d4b12d92ab56dd65fb91efcb5314bd03e

**Comment by seanf316** [comment]
Product sale functionality added - https://github.com/seanf316/PC-Haven/commit/79e446191d963953444335d8d2ac8008e4836c82
