### ISSUE TITLE
USER STORY: Product Search

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#27]
As a **User** I would **like the ability to search for a product** so that **to see if the site sells it**

## Acceptance Criteria
- User has access to a Product Search input that will reference the database for the users requested Product

## Tasks
- [x] Task 1 - Create search view
- [x] Task 2 - Update urls
- [x] Task 3 - Test functionality

**Comment by seanf316** [comment]
Updated action link on search form - 1ff8e0e49bdd364006067593d583793fdec38824

**Comment by seanf316** [comment]
All products view updated to handle product search functionality - e1d4ed4bb06ca42c9cb01a9a6179a8e2f4f0f13d

**Comment by seanf316** [comment]
Customer can search the site for a specific product and if the product name, features or description contain this query the will be presented with a list of products.
