### ISSUE TITLE
USER STORY: Product Search Results Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#28]
As a **User** I would **like to view a page containing the search results from my Product search** so that **so that I can find my prefered Product or see similar Products**

## Acceptance Criteria
- User enters their search query and are shown a page containing all the items that contain their query

## Tasks
- [x] Task 1 - Create Template
- [x] Task 2 - Style Template inline with site theme
- [x] Task 3 - Incorporate the Product Search Results

**Comment by seanf316** [comment]
User story complete by utilising the Products page to display all products from the search input.
