### ISSUE TITLE
USER STORY: Products Page

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#29]
As a **User** I would **like a page that displays All Products the site offers** so that **I can browse and find products that I may want to purchase**

## Acceptance Criteria
- User can access a Products Page that displays all products the site has for sale

## Tasks
- [x] Task 1 - Create View
- [x] Task 2 - Update urls
- [x] Task 3 - Create Template
- [x] Task 4 - Style Template
- [x] Task 5 - Incorporate Products

**Comment by seanf316** [comment]
Created the initial base Products view and updated urls - a83ac961de0a2959e7da5d1ad08a91d5937f2f15

**Comment by seanf316** [comment]
Base Products template created - 1407d8a0f5ded900e98ad6c92490efdff2f220a5

**Comment by seanf316** [comment]
Products template updated with layout and styling - e72671069eabb447b00e48a71fafdb0ad4f4c5da

**Comment by seanf316** [comment]
Created a separate Product Card template to include in the Products template - 6e1b47c52b432e6da871cb0abf0f5254e8571627

**Comment by seanf316** [comment]
A new css file was created for the Products page - b3e8a9adb74ce6b36ab7f0682b0036d4f2ea2db3

**Comment by seanf316** [comment]
Image backup code added to the Products card - 62585a9c88e263d5a4ca6aa844b53669bb8c7c2c

**Comment by seanf316** [comment]
Breadcrumbs added to Products page - 8f1522e07b954b96f72dd41f99edca26710640d6

**Comment by seanf316** [comment]
Category/Sub-Category badges added and Products page headings update to reflect selected category - 2c63b584dbf65f4beeecf4265907b8dd86585030

**Comment by seanf316** [comment]
Product sorting select box added to template and styled - 3eb657d466ace1afbf146bc4bda3b95955f4ec24

**Comment by seanf316** [comment]
Updated product selector with option to sort by sub-category, sortprod.js added - 3ff38cae61b06325e2b8eed30f1b4674c503e3f8

**Comment by seanf316** [comment]
Pagination updated to fix overflow issue on smaller screens if number of pages becomes to long - a00d9ded8a5e260c41fdef4795cb724a785e1e50

**Comment by seanf316** [comment]
Product card updated to include edit/delete links - 83b6a0da5f611d58fc46eff8fee711a781543121
