### ISSUE TITLE
USER STORY: Product Sorting

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#30]
As a **User** I would **like the ability to sort products** so that **I can identity the best priced/rated Products the site offers**

## Acceptance Criteria
- User can sort Products by Price/Rated

## Tasks
- [x] Task 1 - Add Product sorting to the template
- [x] Task 2 - Style inline with site theme
- [x] Task 3 - Test Functionality
