### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#31]
As a **Developer** I can **allow the functionality to edit Products by staff members** so that **they can reduce/increase prices, change product descriptions/images etc**

## Acceptance Criteria
- Staff members can Edit Products

## Tasks
- [x] Task 1 - Create View
- [x] Task 2 - Update Urls
- [x] Task 3 - Create Edit Form
- [x] Task 4 - Create Template
- [x] Task 5 - Style Template inline with site theme

**Comment by seanf316** [comment]
Edit product view created - 10e08e44f7f9baf85131686906460c1824a04d1f

**Comment by seanf316** [comment]
Urls updated to include edit product view - f1071fb0c22e945f567d60d6951174a118b652c2

**Comment by seanf316** [comment]
Edit product template created and styled - 9acabdf83408055e89b26ae9285e33595bd5efac

**Comment by seanf316** [comment]
Changed the name of some product fields to avoid confusion in form - 3b3c393422878ecfcb7bf4a27e7c7894277784f7
