### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#32]
As a **Developer** I can **add functionality for staff members to delete Products** so that **if they do not sell or there is problems with the Product it can be removed from the storefront**

## Acceptance Criteria
- Staff members have the ability to Delete Products

## Tasks
- [ ] Task 1 - Create View
- [ ] Task 2 - Update Urls
- [ ] Task 3 - Update Products Template

**Comment by seanf316** [comment]
Delete Product view created - a0082c6abfeb457c57e4ecad51821116b7281eec

**Comment by seanf316** [comment]
Product urls updated with delete view - 68549712ed516182dfa76a3a73b3f41edc16fb8a

**Comment by seanf316** [comment]
Edit Product template updated to include delete modal - 1b5e6aedeff8c34a23aeb9a1bfbf8fc95ea6a594
