### ISSUE TITLE
USER STORY: Product Details Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#33]
As a **User** I would **like to view the details of any Product** so that **I can see if the Product has the required specifications that I need/want**

## Acceptance Criteria
- User can click on any Product and be brought to the Product Detail Page 

## Tasks
- [x] Task 1 - Create View
- [x] Task 2 - Update URL's
- [x] Task 3 - Create Template
- [x] Task 4 - Style Template

**Comment by seanf316** [comment]
Product Details view created - 1465995064113c08f115bc5d7af4b80f1f46bee1

**Comment by seanf316** [comment]
Products urls.py updated with new view - 4a3afde7154eb5dda9125e12aa6e97d66705ed20

**Comment by seanf316** [comment]
Product Details template created and styled - 9c46664dd1e928cd253d0301b078b12fa1933e65

Further changes are planned.

**Comment by seanf316** [comment]
Product Details updated to include category tag - cb5ecc44222fcf4c6d89bcfa1fab3f58361c6fa3

**Comment by seanf316** [comment]
Added back to top button along with base.js file to be used throughout site - 75d3ae8ab739b64ba5cfbc1aee62eb9e7fec7a9f

**Comment by seanf316** [comment]
Product Detail template updated with Manage Product link - 0dcd9c01633d4268d4a419976b038e72778f7e9e

**Comment by seanf316** [comment]
Product Detail template updated with basic add to cart functionality - 6341fd2de563ae75a0f686764b1bff647a416942

**Comment by seanf316** [comment]
Quantity input added to Product Detail - aeaf45c9c1dd1355e86959ae8e40d1d940137180

**Comment by seanf316** [comment]
Quantity input size reduced - 789bfc920dc0b19b73400316637c3b2c44d86c0a

**Comment by seanf316** [comment]
Added breadcrumbs to product detail page - 891186beb3baf86af1a79c5e0cbdfe8ae50f34e8

**Comment by seanf316** [comment]
Product Detail template updated with Review references - 7fb68454324821ea6d6952b32a24637adb4576f1

**Comment by seanf316** [comment]
Updated prod_reviews with else statement for no review - 78779b45e31746dba6d57f9b8262ff27c32e9d2f
