### ISSUE TITLE
USER STORY: Cart Setup

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#34]
As a **Customer** I would like **to add items that to a cart** so that **I can view all items and purchase or remove items at will.**

## Acceptance Criteria
Customer both Guest/Registered can add items from the Products page to the cart.

## Tasks
- [x] Task 1 - Create Cart app
- [x] Task 2 - Create Cart view, update urls
- [x] Task 3 - Create cart context processor to be available across the site

**Comment by seanf316** [comment]
Cart app created, and base cart view added along with cart.html - 6095e50ccdb31e747958667790296d1f5e55477a

**Comment by seanf316** [comment]
Cart template created - 90f4a59f21baa035cf32272ffdbadcfcf6ccf995

**Comment by seanf316** [comment]
Cart urls updated with view_cart view - ee9b81f3fa70a11ed8258e354c204438a37df782

**Comment by seanf316** [comment]
Cart context processor created - 185df3d4a8c62341966611d8ed27bafd0d2e7472

**Comment by seanf316** [comment]
Added user variable to the context processor - d27ad3b373136f4cf536b2b0b610283e936da51b

**Comment by seanf316** [comment]
Cart tools template tags created for calc|subtotal - 9f7563ee576f34fa42e32913525c0049cd190de5

**Comment by seanf316** [comment]
Updated add to cart view to check request method first - 03c35c5fb57f826295efb82eb40df5805916788d

**Comment by seanf316** [comment]
Carts views updated to show correct messages - c19f6134e7c15da02fcdf252ef2b58f0737f8419
