### ISSUE TITLE
USER STORY: View Cart

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#36]
As a **Customer** I would like **to view all items in my cart** so that **I can manage the items I want to buy.**

## Acceptance Criteria
Customer can click on the Cart icon in nav and view items in the cart.

## Tasks
- [x] Task 1 - Create Cart Template
- [x] Task 2 - Add styling inline with site theme
- [x] Task 3 - Update nav links and references where needed

**Comment by seanf316** [comment]
Cart template created - https://github.com/seanf316/PC-Haven/commit/90f4a59f21baa035cf32272ffdbadcfcf6ccf995

**Comment by seanf316** [comment]
Cart template updated with basic viewing of products - feb7da559a04d65adcfed146ea2e887bfb5da9ba

**Comment by seanf316** [comment]
Cart template updated and styled inline with site theme - 6f969f2c0b3401c8782a3d424d4cdd9df92a88b0

**Comment by seanf316** [comment]
Added padding to cart summary - 7837328e41b6767bc2c17e4a5f190f28c1264872

**Comment by seanf316** [comment]
Cart template updated with link to checkout - a5dd88ae7eb386b486ba414fed2588b35e4bb15f
