### ISSUE TITLE
USER STORY: Free Delivery Threshold

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#37]
As a **Developer** I can **add in functionality to advise customer of free delivery at a certain threshold** so that **customer is aware of delivery costs and can add more items if price is suitable.**

## Acceptance Criteria
Customer is advised in cart view of free delivery threshold and on homepage also, threshold is applied if customer spends the required amount.

## Tasks
- [ ] Task 1 - Create FREE DELIVERY THRESHOLD variable
- [ ] Task 2 - Create DELIVERY CHARGES
- [ ] Task 3 - Update checkout functions to add the above
- [ ] Task 4 - Test

**Comment by seanf316** [comment]
Delivery Variables updated to Shipping variables - 7e7610de0b7ccb025668c66482a5a217dad5bd51

**Comment by seanf316** [comment]
FREE SHIPPING THRESHOLD value updated - 2aed5248ff484103a3e1e33ab347dbd15349f815
