### ISSUE TITLE
USER STORY: Checkout View

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#42]
As a **Developer** I can **create a checkout page** so that **the customer can enter their billing/shipping/payment information to complete purchase.**

## Acceptance Criteria
User clicks checkout in cart view and checkout page is displayed

## Tasks
- [x] Task 1 - Create checkout view
- [x] Task 2 - Update urls
- [x] Task 3 - Add link to cart page
- [x] Task 4 - Test

**Comment by seanf316** [comment]
Checkout models registered - 45c1f3bcddea0db0fd54abcd34e1a22e129a942a

**Comment by seanf316** [comment]
Added forms, admin and signals - 222846fc26cbf224210c7499fd96c0d91caf013a

**Comment by seanf316** [comment]
checkout view created and updated with stripe functionality - 349c847627c239810b0643246561298ef66f7ee4

**Comment by seanf316** [comment]
checkout urls created and updated with new checkout view - db231c37167966b2860e43e93ba3221932722c65

**Comment by seanf316** [comment]
checkout template created and styled - 5fc8f8dd190236fb78bee076ffe3dded681d02c5

**Comment by seanf316** [comment]
checkout css created and stripe_elements.js added - 28357a9b5e6bc9e854b60d8ff8d952b54528f84d

**Comment by seanf316** [comment]
Fixed update_total on Order model - 35e4727e207e0082e2cd9cb9826ba95396b98fee

**Comment by seanf316** [comment]
Checkout view updated with order functionality - f7882cf2c5fceaba09da2d9607616eb78c6ae7fd

**Comment by seanf316** [comment]
checkout success view created - f0200a9e2067ed0eb8dea1d563e55c8307774c5f

**Comment by seanf316** [comment]
Updated checkout urls with new view - db5ddca446c1fbcf6a96e2ab49cd4be0d40c3922

**Comment by seanf316** [comment]
Base checkout success template created - 49988b5f51ea33370f3a244f7c840797aac31428

**Comment by seanf316** [comment]
Order model updated with Profile reference - f71272699ec09033ebde79751dcd83274aad69fe

**Comment by seanf316** [comment]
Checkout view updated with profile references - 358f56a2556b64f6fc640559f11ae39be2125e16

**Comment by seanf316** [comment]
user_profile field updated in Checkout admin - 790ec9f82301d0c4bd98597c001516d7157610dd
