### ISSUE TITLE
USER STORY: Edit Cart Items

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#43]
As a **Customer** I would **like the ability to edit the quantity of an item in my cart** so that **I can update the amount I want to buy of a specific item**

## Acceptance Criteria
Customer can update the quantity of an item in their cart

## Tasks
- [ ] Task 1 - Create edit cart view
- [ ] Task 2 - Updated urls with new view
- [ ] Task 3 - Update cart template

**Comment by seanf316** [comment]
Edit cart view created - d6b5aa5706372e2a98f60d6e0640e2c13e5737f7

**Comment by seanf316** [comment]
Cart template updated - 6f969f2c0b3401c8782a3d424d4cdd9df92a88b0
