### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#44]
As a **Customer** I would **like to remove an item from my cart** so that **if i decide its not what I want i can easily remove that item and continue purchase with the rest of my cart items**

## Acceptance Criteria
Customer can delete and item from their cart

## Tasks
- [ ] Task 1 - Create delete_from_cart view
- [ ] Task 2 - Update urls with new view
- [ ] Task 3 - Update cart template

**Comment by seanf316** [comment]
Delete from cart view created - 00cad606cb5d9908e901f29ffd00b3354b1a6c81

**Comment by seanf316** [comment]
Cart urls updated with delete views - 12fbbe91a6ef4766a8414a2e78796b8330e4c627
