### ISSUE TITLE
USER STORY: Site Toasts

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#45]
As a **Developer** I can **implement message toasts** so that **the user/customer is alerted when they carry out and action or encounter and error.**

## Acceptance Criteria
Messages display when user carries out action that has a corresponding message in the view

## Tasks
- [x] Task 1 - Update Base Html with toasts
- [x] Task 2 - Add js
- [x] Task 3 - Create toast templates
- [x] Task 4 - Style templates

**Comment by seanf316** [comment]
Toasts created and updated in base.html - 3b7886a7e9077d7b71248dcb6cb04ed17049cc85

**Comment by seanf316** [comment]
message.js created for toasts - ea48d666693a78439bd864e4bbe99892cf0a5c7e

**Comment by seanf316** [comment]
settings.py updated with Message Storage variable - 1e49e50c5e9d50f408ff98715e65ecbc54c74da7

**Comment by seanf316** [comment]
Styling added to toast messages - 2085c3ed92f67283094a4023ae868ff613ecaa13

**Comment by seanf316** [comment]
Success toast updated to check if product contains image and render correctly - 0b0604c9bb6178706f17cfc0ea5d7f48e8754f9b

**Comment by seanf316** [comment]
toasts updated to hide on scroll-cdf5e99d0151de5381f30b3f7cf41c6cbb21477c
