### ISSUE TITLE
USER STORY: Stripe Setup

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#46]
As a **Developer** I can **implement Stripe** so that **it can manage payments for the site products at checkout**

## Acceptance Criteria
Customer can enter card details and checkout or be informed if there are issues

## Tasks
- [x] Task 1 - Create Card Element
- [x] Task 2 - Add JS to handle payment/errors
- [x] Task 3 - Update Checkout with Card Element
- [x] Task 4 - Style Card element

**Comment by seanf316** [comment]
Stripe js script added to corejs block - https://github.com/seanf316/PC-Haven/commit/86f36b7895a4c026ea30ecc5876142ec7acc4bc0

**Comment by seanf316** [comment]
Stripe variables updated in settings.py - 6e6106aa2a2f13eae42a92ee6f16d4212306a6b5

**Comment by seanf316** [comment]
stripe_elements.js added - https://github.com/seanf316/PC-Haven/commit/28357a9b5e6bc9e854b60d8ff8d952b54528f84d

**Comment by seanf316** [comment]
Stripe webhooks added - e82dc7c638313f85222353ff83b788753dd629cc

**Comment by seanf316** [comment]
Webhook handler updated to reference Profile - c994cd1876c1505a667769c9230dface7597ccb3
