### ISSUE TITLE
USER STORY: User Profile Setup

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#47]
As a **customer** I would like **the ability to create my own Profile page** so that **I can save my shipping address for future purchases and track my orders**

## Acceptance Criteria
When customer registers on site they will have access to their own Profile page where they can add/edit/delete their information

## Tasks
- [x] Task 1 - Create Profile views
- [x] Task 2 - Update urls
- [x] Task 3 - Add CRUD functionality

**Comment by seanf316** [comment]
Profile app created - 1bae387373d07c349f75cf34ecb6fb5bdaa8a004

**Comment by seanf316** [comment]
User Profile model created - 984e90ffded4ffc06caffe79acfd52214dd5885c

**Comment by seanf316** [comment]
Profile app added to settings.py - 7d047d5dad2a7ed986ceb23611384e4d156e77c6

**Comment by seanf316** [comment]
Base profile view created - 8a51007c85f3e3682b93e535f93447961c306955

Further updates to come.

**Comment by seanf316** [comment]
Profile urls updated with profile view - 8396bb2725a45e3d2e16d198d2d3164c79f252e3

**Comment by seanf316** [comment]
Main urls updated with Profile urls - 6c6f14643e978cc641543151961d3e7145a2ec86

**Comment by seanf316** [comment]
User form and UserProfile form created - a7c6f8e49f7ff03985f06cd78501eb65c16961a6

**Comment by seanf316** [comment]
Profile view updated with forms - 76857896809595d373aefd641dec130a91065472

**Comment by seanf316** [comment]
Added firstname & lastname on Userform - https://github.com/seanf316/PC-Haven/commit/2b30d226011eee490858cf941a58faa98fa06769

**Comment by seanf316** [comment]
Order history view created - 52b9ecf9fa2512213d35a26ca0a8f6e93ab831ee

**Comment by seanf316** [comment]
Profile urls updated with order_history path - 2cd424692960ee2ec241583cbd081f37a5503774

**Comment by seanf316** [comment]
Added ordering meta to Order model - 9b05f5938a5ca56dcb2f371bb55227f7f223cb62

**Comment by seanf316** [comment]
Added login required to Profile views - 9c6302d6361cb34d75271023982099fb9d515fef
