### ISSUE TITLE
USER STORY: Profile Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#48]
As a **Developer** I can **implement functionality to allow a customer to save information to a personal Profile** so that **they can save information i.e. shipping address/orders for future review**

## Acceptance Criteria
Customer can click Profile link and be brought to a page containing their information

## Tasks
- [x] Task 1 - Create Profile Page
- [x] Task 2 - Style Profile Page
- [x] Task 3 - Add links where required

**Comment by seanf316** [comment]
Profile template created - 88ea4386f0f9529f24502f26f13469befee82e8b

**Comment by seanf316** [comment]
country_field.js added to fix css on country field - f1e3fafff224f11a5d6d42a1a6ac3493c092601f

**Comment by seanf316** [comment]
Added firstname & lastname on Userform - 2b30d226011eee490858cf941a58faa98fa06769

**Comment by seanf316** [comment]
Profile template updated with wishlist content - 30677de66cd46a383f749f61b7f54c5507c9bfa5

**Comment by seanf316** [comment]
Wishlist Product cards updated with remove anchor - 7839990c20fe9a39247c389a20e1038b96e2b386

**Comment by seanf316** [comment]
Profile template updated with {else} content in Order History and Wishlist - 1f6aa4550d5ec449bd253afca96fde5df2cd797c

**Comment by seanf316** [comment]
Profile template updated with clear wishlist anchor - bc82112c7d66fb291beefc7c21b6500b608a1898

**Comment by seanf316** [comment]
Profile template refactored with inlcudes - 7f80766c17e19fbf81e35aa31269b007bcfcf447
