### ISSUE TITLE
USER STORY: Wishlist

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#49]
As a **Customer** I would **like the ability to add products to a Wishlist** so that **I can keep a list of my products to purchase in the future**

## Acceptance Criteria
Customer and add Products to Wishlist

## Tasks
- [x] Task 1 - Create Model
- [x] Task 2 - Create View
- [x] Task 3 - Update Urls
- [x] Task 4 - Update Templates

**Comment by seanf316** [comment]
Wishlist model created in Profile app - 5a8ac358140bf35b56c968150d61080e61db7e64

**Comment by seanf316** [comment]
Profile view updated with wishlist reference - 7d5e9cd91aa3022ffe81cf911a7ca587414f6cf7

**Comment by seanf316** [comment]
Add to wishlist view created - 74127fdf73b63d04f0dbee6fc693b707584c183a

**Comment by seanf316** [comment]
Profile urls updated with add to wishlist path - b8bda836bc0379b91139b5bc617343436876ce46

**Comment by seanf316** [comment]
Updated add to wishlist redirect method - 5ddc7de086e9d9e2b74a9c0c727624965d67a7e0

**Comment by seanf316** [comment]
Remove from Wishlist view created - ab86d8dbb41194d96590ed1b257b500730acb10c

**Comment by seanf316** [comment]
Profile urls updated with new view path - 3d5b4a52c1fa1c39b063a688cea76ceb912850ee

**Comment by seanf316** [comment]
Clear wishlist view created - 31ec2e1c74c53a5dabd6a8d51b8a0511921d3f99

**Comment by seanf316** [comment]
Profile urls updated with clear wishlist path - 9017a0f088e708c8105456e79d6ba129640aba3b
