### ISSUE TITLE
USER STORY: Blog Setup

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#53]
As a **Developer** I can **create the functionality for site admin to add Blog Posts** so that **customer may spend more time on the site which may lead to more purchases.**

## Acceptance Criteria
Site admin can add Blog Posts

## Tasks
- [x] Task 1 - Create Blog App
- [x] Task 2 - Create Blog Views
- [x] Task 3 - Create Blog Urls

**Comment by seanf316** [comment]
Blog app created - 129126e19a575413f45919322e1c2187f91ad223

**Comment by seanf316** [comment]
Blog model created - 51ed4c8eeaef69958224bb396afc4e224585fe28

**Comment by seanf316** [comment]
Blog form created - 5a73f44b4f89771afff91528c98e300ca0beaf8d

**Comment by seanf316** [comment]
Blog urls created and new view updated - 130c2a39d933b9a97840f84f930705b693c3907e

**Comment by seanf316** [comment]
Blog model registered - 0d44682008c879b8422284962d17aceaab9a5084

**Comment by seanf316** [comment]
settings.py Installed Apps updated with blog - 3969b0d272de86d5a6b56803b12211f0dff40fec

**Comment by seanf316** [comment]
Main urls updated with blog urls - 435fc2f0c604dbc5f4c3bcd6cfaac42cb1f45e35

**Comment by seanf316** [comment]
blog_detail & likes views created - a015b1be6e07b6c8b7633c3919be1d0f48e8551b

**Comment by seanf316** [comment]
Blog urls updated with new views - 46f7315242cbe1d8425ff7811d39b0cbcabbfc60

**Comment by seanf316** [comment]
Add blog view created - ba16b156dbc2bbd66fd0bcc1718751140eafdc1c

**Comment by seanf316** [comment]
Blog urls updated with the new view - 70a5f711e6a99b96d96e0d25483e7fcae698de3e

**Comment by seanf316** [comment]
Edit blog view created - f7a8919fc68fcaa85461cce960afcf9da98879cb

**Comment by seanf316** [comment]
Delete blog view created - 1d18b189780b5d7c2c0510c7c99a65e4ec83ad07

**Comment by seanf316** [comment]
Blog urls updated with delete view path - 79b4f67a33ebff966670160f63352e951e1e4e4b

**Comment by seanf316** [comment]
Pagination added to blogs view - e8fc51fad1548268cfb6ca80b75494af051e7c18

**Comment by seanf316** [comment]
Comment Model created - 66b228d5f5a9a491fefe2ea4b12244dacbde1b8d

**Comment by seanf316** [comment]
Comment form created - 8aa33b6d692e002c07fe4e542271c67360aa8a97

**Comment by seanf316** [comment]
[Add comment view created and blog view updated](https://github.com/seanf316/PC-Haven/commit/2f47c59a260499b034582ebcc56ff49dd9208691)

**Comment by seanf316** [comment]
Blog urls updated with add comment - 0ef7d0ee74efc8fdbeaa743cc0482e9e02b4dace

**Comment by seanf316** [comment]
Add comment page created - f1f284aaa5513cb65ae0a878af5317b1d3160635

**Comment by seanf316** [comment]
Added edit/delete comment, add comment updated - 831e81145ec1e4ce2b79e6fcd5831121d7ef48c2

**Comment by seanf316** [comment]
blog urls updated with edit/delete comment views - f88e10ffe42ac338a875ebc4edbe515f0efbc317
