### ISSUE TITLE
USER STORY: Blog Templates

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#54]
As a **Developer** I can **build some Blog related templates** so that **the site admin can display blog posts on their site for a good customer experience**

## Acceptance Criteria
When customer clicks Blog link site Blog Posts are displayed

## Tasks
- [x] Task 1 - Create Blog related templates
- [x] Task 2 - Style Templates
- [x] Task 3 - Update Navbar links

**Comment by seanf316** [comment]
Blog template created and styled - 688792b16e6b1a53e098c37bc3ec84eeddc146b0

**Comment by seanf316** [comment]
Fixed Blog forms fields - 2556badaf1bd5fd5fa13c37e01ca222e957a3edb

**Comment by seanf316** [comment]
Blog Detail template created and styled - 241067aecc30b01b3050926499ef3342683c4852

**Comment by seanf316** [comment]
Added clearable widget to the Blog form - f058692aa8c4868d0d7849f9614c9f77b0e30e9c

**Comment by seanf316** [comment]
Add Blog template created - ca6f5060eeaabfe8031663bf9790e31d398047e2

**Comment by seanf316** [comment]
Manage blog references added to Blog pages - cc6bd8a51eb913b9416a0ae7f4c1ec885761d41d

**Comment by seanf316** [comment]
Edit blog template updated with delete url - 4f493c7abd9a24e79ccdc656bb671e7d9e25b412

**Comment by seanf316** [comment]
Updated styling on Blog templates - 4c99d7fd6669ed59aac7f40de24c40a331f0000e

**Comment by seanf316** [comment]
Pagination added to blogs template and includes added - e8fc51fad1548268cfb6ca80b75494af051e7c18

**Comment by seanf316** [comment]
Blog templates updated and styled - fb3a6deee9f29c4bc0c3a4695bfc71446fa0312c

**Comment by seanf316** [comment]
Blog templates styling/content updated - d64822f1fb23eb6de7d1aba1a4d152dd6f829345

**Comment by seanf316** [comment]
edit comment template created - ae0f9640187ef16dee8c6c885b5a94f7d76822da
