### ISSUE TITLE
USER STORY: Contact Us

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#58]
As a **Developer** I can **add functionality to allow the customer to contact the site owner** so that **any issue they encounter can be logged and resolved**

## Acceptance Criteria
Customer can click contact link and submit a contact form

## Tasks
- [x] Task 1 - Create Contact App
- [x] Task 2 - Create Contact Views
- [x] Task 3 - Create Contact Urls

**Comment by seanf316** [comment]
Contact app created - 108b895b019a5a9579f1b182cb230cbabd2b23de

**Comment by seanf316** [comment]
Contact model created - 1f4faf439483ae2d0f43e73c48a37f03067fbc52

**Comment by seanf316** [comment]
Contact form created - 69e0824f8a9b686123f862f32490fea27933a08e

**Comment by seanf316** [comment]
Contact model registered in admin - df4b9a24ae91a4e811b529879b909921d11b3c04

**Comment by seanf316** [comment]
Contact app added to settings.py Installed apps - e0f60d36e88c3e7dcac9341823cf349081f03b7b

**Comment by seanf316** [comment]
Contact view created - 10666fcee8bac34f4a74c05c75f6f8096a1bb794

**Comment by seanf316** [comment]
Contact urls created and new path added - f82f484a544a80fcf82bde42bd809dbb846b15c2

**Comment by seanf316** [comment]
Main urls updated with Contact urls - 2a102a8a29da8200b8d57d3a7a4b1b7d6fdddce5

**Comment by seanf316** [comment]
Contact template created - 4045b479e7103a82aa632a6bbab69e24ffa18d23
