### ISSUE TITLE
USER STORY: SEO Implementation

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#60]
As a **Developer** I can **add helpful description and keywords** so that **my site can reach a wider audience**

## Acceptance Criteria
Add site short tail/long tail keywords

## Tasks
- [x] Task 1 - Signup to Wordtracker
- [x] Task 2 - Research keyword phrases
- [x] Task 3 - Implement keywords into code

**Comment by seanf316** [comment]
Added site SEO description & keywords -Haven/commit/da2f85099a1412b4650a6e674e0f3972467778f9

**Comment by seanf316** [comment]
Robots.txt and sitemap added - d56f4fa5abf09d8c67552d912a03b462d0034f12

**Comment by seanf316** [comment]
Favicon added - 07b23737a9cd544eadf2a44d4e2c6fa0dcc54d42

**Comment by seanf316** [comment]
Updated views/urls/pages with slugs for SEO - 491cab78a3a34db79c9e879b4c8553cab4390fc3

**Comment by seanf316** [comment]
Blog views/urls/pages updated with slug for SEO - a14dd7fb97328b6c3843fa9ec7d4e2841a277ea2
