### ISSUE TITLE
USER STORY: Mailchimp Newsletter

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#62]
As a **Developer** I can **implement a newsletter on my site** so that **customers can subscribe for future updates and deals which should bring them back to the site for future purchases.**

## Acceptance Criteria
Your can subscribe to the site Newsletter

## Tasks
- [x] Task 1 - Create Mailchimp Account
- [x] Task 2 - Setup Embedded form
- [x] Task 3 - Add form and js to site code

**Comment by seanf316** [comment]
Newsletter created and Mailchimp JS added - 91c74317c8788286f3cb97852e38d6491d3c43b4

**Comment by seanf316** [comment]
mailchimpjs removed - placed in index - 905a7286271896c972cd2d602c2b1052c8e11cfc
