### ISSUE TITLE
USER STORY: README.md

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#64]
Create/Write README.md

## Acceptance Criteria
- Readme available on Github

## Tasks
- [x] Task 1 - Write site overview
- [x] Task 2 - Write Table of Contents
- [x] Task 3 - Write sections for Table of Contents
- [x] Task 4 - Create Gifs/Screenshots of site

## Epic: #63

**Comment by seanf316** [comment]
README updated with Overview/Strategy/EPICs - (https://github.com/seanf316/PC-Haven/commit/1dc35e2564be93f35944a90be20b51ff2f7cc866)

**Comment by seanf316** [comment]
User Stories added to README - https://github.com/seanf316/PC-Haven/commit/22b68ecc3d1ccf0d270db908a516b27c27e92de5

**Comment by seanf316** [comment]
Wireframes added to README - https://github.com/seanf316/PC-Haven/commit/1d5080ec0d4bf9a9591b84ffb8cb137d568d89a9

**Comment by seanf316** [comment]
Database Diagram added to README - https://github.com/seanf316/PC-Haven/commit/9931494d989ee25153772348b734567d5a09df18

**Comment by seanf316** [comment]
Homepage features added to README - https://github.com/seanf316/PC-Haven/commit/c4d4a62a5b7fb763f1438a1853c1d6f07f0ce2fc

**Comment by seanf316** [comment]
README Features finished - https://github.com/seanf316/PC-Haven/commit/87800a0f00a8feef657c052f8b0c763626e90c9a

**Comment by seanf316** [comment]
DEPLOYMENT.md created and linked in README.md - https://github.com/seanf316/PC-Haven/commit/dac5a97b9ad1f48b7cee34a12113ab48d69acbcd

**Comment by seanf316** [comment]
SEO/Web Marketing added to Readme - https://github.com/seanf316/PC-Haven/commit/2766ce21ffb972c8c2b5681a1df396d1e55e5a17

**Comment by seanf316** [comment]
Updated Table of Contents in Readme - https://github.com/seanf316/PC-Haven/commit/39d6062d7d9d4a1ef38e5183423e565d3516cc5c
