### ISSUE TITLE
USER STORY: TESTING.md

### ISSUE THREAD

**Issue by seanf316** [seanf316/PC-Haven#65]
Create/Write TESTING.md

## Acceptance Criteria
- Testing carried out and updated in TESTING.md

## Tasks
- [x] Task 1 - Complete HTML Validation
- [x] Task 2 - Complete CSS Validation
- [x] Task 3 - Complete JS Validation
- [x] Task 4 - Complete Python Validation
- [x] Task 5 - Provide Unit testing
- [x] Task 6 - Complete Manual Testing
- [x] Task 7 - Create screenshots for TESTING.md

## Epic: #63

**Comment by seanf316** [comment]
TESTING.md created and Manual Testing started - https://github.com/seanf316/PC-Haven/commit/0540f184aeafa66c7c16612c4c5343e79638262a

**Comment by seanf316** [comment]
Checkout/Order/Profile Testing added - https://github.com/seanf316/PC-Haven/commit/43173f3d3039e9b2e7d1ae9a1ce779176c1a28f3

**Comment by seanf316** [comment]
Blog/Contact Testing added to Testing.md - https://github.com/seanf316/PC-Haven/commit/83179c362c0b4f950eb920c2bab5d3850f5c2f34

**Comment by seanf316** [comment]
User testing section completed in TESTING.md - https://github.com/seanf316/PC-Haven/commit/a63f05bdf4c75292f3ebef0053082ad281924bdc

**Comment by seanf316** [comment]
JS Testing/Validation added to TESTING.md - https://github.com/seanf316/PC-Haven/commit/081d7d93a8b29a42e6f2feaa1f7b2c6a3b6e0638

**Comment by seanf316** [comment]
CSS/HTML Validation completed - https://github.com/seanf316/PC-Haven/commit/0a6ebb1464237ff4222dcd11cf2e7ccfe8334494

**Comment by seanf316** [comment]
TESTING.md validation updated - https://github.com/seanf316/PC-Haven/commit/e50c664a4ae5b0a8ffb1858519a8a1dd25059a9b

**Comment by seanf316** [comment]
TESTING.md updated with Unitesting - https://github.com/seanf316/PC-Haven/commit/9218b3c353b13021d8abe2e3cbe661bf1d94fa52

**Comment by seanf316** [comment]
Pep8 lint results added to TESTING.md - https://github.com/seanf316/PC-Haven/commit/49ac1189bfaa5ffdd725fb5d07cf1fdd9fee59df

**Comment by seanf316** [comment]
Documentation ran through Grammarly - https://github.com/seanf316/PC-Haven/commit/21e2a87441cf8ec0f5beff92fd6ed0fb5ebed421

**Comment by seanf316** [comment]
TESTING.md typos corrected - https://github.com/seanf316/PC-Haven/commit/0307b5db76f47fb07bcb052e768658db1e87760b
